import React from 'react';
import ExperimentalModel from './ExperimentalModel.jsx';

const repo = 'https://github.com/itej13/uganda-rain-atlas';
const sources = [
  ['CHIRPS v3', 'Rainfall history', '0.05° (~5 km) · 1981–present', 'Pentads and months; daily series are disaggregated. Useful for seasonal patterns, not minute-by-minute onset.', 'https://www.chc.ucsb.edu/data/chirps3'],
  ['NASA GPM IMERG', 'Satellite rainfall estimates', '0.1° (~11 km) · every 30 minutes', 'Early Run typically arrives about 4 hours later. Useful for independent satellite verification, not immediate rain detection.', 'https://gpm.nasa.gov/data/imerg'],
  ['Copernicus ERA5', 'Historical weather fields', '0.25° (~28 km) · hourly · 1940–present', 'Consistent rainfall, humidity, temperature and wind. Retrospective reanalysis, not ground truth or an as-issued forecast.', 'https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels'],
  ['TAMSAT v3.1', 'African rainfall history', '0.0375° (~4 km) · 1983–present', 'Daily satellite rainfall estimates covering Uganda. Useful for drought, seasonality and rainfall verification.', 'https://www.tamsat.org.uk/data'],
  ['Meteosat / EUMETView', 'Near-real-time cloud changes', 'Infrared · 10-minute cadence', 'Country-wide cloud imagery used on this map. Capture time and feed age are shown; cold cloud tops do not prove rain at ground level.', 'https://user.eumetsat.int/resources/user-guides/eumet-view-user-guide'],
  ['Open-Meteo', 'Operational model forecasts', 'Hourly · global coverage', 'Provides the public map’s forecast. Rain probability uses ensemble models at about 0.25°; the map does not add spatial precision.', 'https://open-meteo.com/en/docs'],
  ['Uganda DMS & TAHMO', 'Local stations and expertise', 'Station-specific coverage and access', 'The best next step for local validation. Station records may require an agreement; restricted data are not republished here.', 'https://wids.mwe.go.ug/'],
];

export default function Research({ page, onMap, selected, now }) {
  return <article className="research-page"><button className="text-button back-button" onClick={onMap}>← Back to the rain map</button>
    <h1>{page === 'about' ? 'Built for a changeable sky.' : 'Know what is behind the forecast.'}</h1>
    <p className="research-lead">{page === 'about' ? 'Rain Atlas brings Uganda’s public weather forecasts, satellite cloud images and rainfall research into one open, accessible place.' : 'Useful predictions start with the right data—and a clear account of what those data can tell us.'}</p>
    {page === 'about' ? <>
      <section className="reading-section"><h2>Rain is variable, but it has patterns.</h2><p>Uganda’s rainfall varies by season, terrain and proximity to Lake Victoria. Much of the south has two main wet seasons, while the north has a longer wet period. Local storms still make the exact time and place of a shower difficult to predict.</p><p><a href="https://wids.mwe.go.ug/">Uganda’s Department of Meteorological Services</a> publishes official forecasts and alerts. Rain Atlas is an independent public project and does not issue official weather warnings.</p></section>
      <section className="reading-section"><h2>Open by design.</h2><p>No account is needed to explore the map. Forecast and satellite requests are cached; refresh retrieves the latest available response. We do not collect location histories. If you choose “Use my location,” the coordinate is sent to this site’s forecast endpoint and Open-Meteo to retrieve weather.</p><p>This is a noncommercial project using the <a href="https://open-meteo.com/en/terms">Open-Meteo free service</a>. Commercial use or larger traffic requires the appropriate provider plan. No payment service or paid data subscription is enabled.</p><a className="primary-link" href={repo}>Explore the source on GitHub ↗</a></section>
    </> : <>
      <section className="method-summary"><div><span className="section-label">On the rain map</span><h2>Weather forecasts</h2><p>Hourly probabilities and amounts come from Open-Meteo’s operational weather models. A 60% chance means a modeled probability of more than 0.1 mm in the displayed hour. It is not 60% of Uganda, or 60% of the hour.</p><p>The interval is shown explicitly in East Africa Time. “Retrieved” is when our server fetched the data, not when the weather model last ran.</p></div><div><span className="section-label">On the satellite map</span><h2>Observed cloud changes</h2><p>Meteosat infrared images show developing cloud systems over the entire country, day and night. Images are normally published at a 10-minute cadence, with a processing delay.</p><p>Brighter, colder cloud tops can help identify convection. This site does not convert cloud brightness into rain probability or portray the imagery as ground radar.</p></div></section>
      <section className="dataset-section"><div className="section-heading"><h2>Data available for Uganda</h2><a href={`${repo}/blob/main/docs/DATA_RESEARCH.md`}>Full research notes ↗</a></div><p className="muted">Primary sources reviewed 15 September 2026. Resolution describes the source, not guaranteed local accuracy.</p><div className="dataset-table"><table><thead><tr><th scope="col">Dataset</th><th scope="col">Coverage & resolution</th><th scope="col">Best use & limitation</th></tr></thead><tbody>{sources.map(([name,kind,coverage,description,url]) => <tr key={name}><th scope="row"><a href={url}>{name} ↗</a><small>{kind}</small></th><td>{coverage}</td><td>{description}</td></tr>)}</tbody></table></div></section>
      <ExperimentalModel location={selected} now={now}/>
      <section className="reading-section"><h2>The next step toward better local prediction</h2><ol><li>Pair time-stamped satellite images and archived, as-issued forecasts with independent IMERG and licensed rain-gauge measurements.</li><li>Test one-hour and three-hour rain events separately, holding out later wet seasons and entire locations.</li><li>Compare with climatology, persistence and the current weather provider using Brier score, calibration, missed events and false alarms.</li><li>Publish measured improvements and uncertainty before calling the new model locally validated.</li></ol></section>
    </>}
    <section className="attribution-section"><h2>Sources & attribution</h2><p>Forecast data: <a href="https://open-meteo.com/">Open-Meteo</a>, CC BY 4.0. Satellite imagery: <a href="https://www.eumetsat.int/">EUMETSAT Meteosat</a> via EUMETView. Map: <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>. Uganda boundary: <a href="https://www.geoboundaries.org/api/current/gbOpen/UGA/ADM0/">geoBoundaries / OpenStreetMap / Wambacher</a>, ODbL 1.0. Individual datasets retain their own access and licence terms.</p></section>
  </article>;
}
